### PR TITLE
Bump runtime to 44

### PR DESCRIPTION
**Pull request by bbhtt**

### CODE REVIEW

**Comment by hfiguiere** [comment]
you should remove jack because it's in the the runtime now.

(that's not the build failure tough which is Python related)

**Comment by bbhtt** [comment]
> (that's not the build failure tough which is Python related)

It's probably an issue with setuptools in flatpak environment, I don't know a way to fix this. Building it in isolation with older setuptools, wheel and cython doesn't seem work and `python setup.py install` fails, presumably for the same reason.

(I had the same issue before on a different application/python module and the 'solution' we came up with is to switch that to meson)

**Comment by mikacousin** [comment]
@hfiguiere Thanks, i will remove jack.

@bbhtt I see that python3-python-rtmidi build fails with "The 'pthread' library is required to build python-rtmidi onLinux. Please install the libc6 development package.". I don't know what to do because I assume that libc6 is present in the environment to build packages...

I'm on tour right now, watching whenever I have a moment

**Comment by bbhtt** [comment]
> I see that python3-python-rtmidi build fails with "The 'pthread' library is required to build python-rtmidi onLinux. Please install the libc6 development package.". I don't know what to do because I assume that libc6 is present in the environment to build packages...

No, I think that's somehow leaking into the error. libc6-dev present in the SDK, the actual error is after that:

```python
    try:
      import setuptools
  except ImportError as error:
      print(
          "ERROR: Can not execute `setup.py` since setuptools is not available in "
          "the build environment.",
          file=sys.stderr,
      )
      sys.exit(1)
  ```

However setuptools _is_ included as well in the runtime.

**Comment by mikacousin** [comment]
I just did some tests and the only solution I see is with this PR in python-rtmidi : https://github.com/SpotlightKid/python-rtmidi/pull/119. Have to ask if it can be merged.
But there is another problem now: it seems that localhost resolution fails. Very strange...
Also, python-psutil no longer lists all processes on the machine.
Flatpak has become very strict ?
I keep looking, but if you have an idea...

**Comment by eli-schwartz** [comment]
> No, I think that's somehow leaking into the error. libc6-dev present in the SDK, the actual error is after that:

That's not the error that's being printed out. That's a bit of the string being passed to `python3 -c ...` in the running process that produced the build output and intermingled error message ending in:

```
  Detected JACK version 1.9.21.
  JACK version is recent enough to have 'jack_port_rename' function.
  The 'pthread' library is required to build python-rtmidi onLinux. Please install the libc6 development package.
  error: subprocess-exited-with-error
```

**Comment by mikacousin** [comment]
@eli-schwartz As I understand it, at the same time, outside of setuptools, it works:
 ```
$ flatpak run --share=network --devel --command=python org.gnome.Sdk
Python 3.10.6 (main, Nov 10 2011, 15:00:00) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ctypes.util import find_library
>>> find_library("pthread")
'libpthread.so.0'
>>>
```
I don't master enough, I'm lost

**Comment by eli-schwartz** [comment]
If nothing else, the meson PR you linked to can help out here by providing significantly better logging and visibility into build issues, and standard frameworks for doing many things that setuptools lacks and projects are currently open-coding with the ctypes module.

I just happen to think the current issue is significantly weirder than just "setuptools isn't installed".

**Comment by bbhtt** [comment]
> I just did some tests and the only solution I see is with this PR in python-rtmidi : https://github.com/SpotlightKid/python-rtmidi/pull/119. Have to ask if it can be merged.


If I'm not mistaken that PR seems to be depending on https://github.com/scikit-build/ninja-python-distributions, until https://github.com/scikit-build/ninja-python-distributions/issues/127 is resolved it can't be built in Flathub (the build is done offline)

**Comment by mikacousin** [comment]
Finally the draft branch of python-rtmidi is build by flathub.
THANKS !

**Pull request closed without merging**
